package eep.view;

import eep.controller.InventoryController;
import eep.controller.LoginController;
import eep.view.DataAccessLayer;
import eep.view.LoginView;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

/******************************************************************************
 * File:NewJFrame.java
 * Course: 17655
 * Project: Assignment 2
 * Copyright: Copyright (c) 2009 Carnegie Mellon University
 * Versions:
 *	1.0 November 2009 - Initial rewrite of original assignment 2 (ajl).
 *
 * This class defines a GUI application that allows inventory to be added to the
 * inventory databases. There are tree tables in the inventory database: trees,
 * shrubs, and seeds.
 *
 ******************************************************************************/
/*
 * AddInventoryMainFrame.java
 *
 * Created on Jan 29, 2010, 9:24:23 PM
 */

/**
 *
 * @author lattanze
 */
public class InventoryView extends javax.swing.JFrame {

    String versionID = "v3.0.0";
    private InventoryController controller;
    String userNameLocal = "";

    /** Creates new form AddInventoryMainFrame */
    public InventoryView(InventoryController controller) {
        this.controller = controller;
        initComponents();
        jLabel1.setText("Inventory Management Application " + versionID);        
    }
    
    public InventoryView(InventoryController controller, String userName) {
        this(controller);
        userNameLocal = userName;
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDBIP = new javax.swing.JTextField();
        txtProdID = new javax.swing.JTextField();
        txtProdPrice = new javax.swing.JTextField();
        btnProdQuantity = new javax.swing.JTextField();
        btnAddItem = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMessageArea = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtProdDescription = new javax.swing.JTextField();
        btnListInventory = new javax.swing.JButton();
        btnDeleteItem = new javax.swing.JButton();
        btnDecrement = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        rdbtnTrees = new javax.swing.JRadioButton();
        rdbtnSeeds = new javax.swing.JRadioButton();
        rdbtnShrubs = new javax.swing.JRadioButton();
        rdbtnCultureBoxes = new javax.swing.JRadioButton();
        rdbtnGenomics = new javax.swing.JRadioButton();
        rdbtnProcessing = new javax.swing.JRadioButton();
        rdbtnRefMaterials = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("EEPs Inventory Management Application");

        jLabel2.setText("Product ID");

        jLabel3.setText("Price");

        jLabel4.setText("Quantity");

        txtDBIP.setText("localhost");

        btnAddItem.setText("Add Item");
        btnAddItem.setActionCommand("jButton1");
        btnAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddItemActionPerformed(evt);
            }
        });

        txtMessageArea.setColumns(20);
        txtMessageArea.setRows(5);
        jScrollPane1.setViewportView(txtMessageArea);

        jLabel5.setText("Product Description");

        jLabel6.setText("Database Server IP");

        txtProdDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProdDescriptionActionPerformed(evt);
            }
        });

        btnListInventory.setText("List Inventory");
        btnListInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListInventoryActionPerformed(evt);
            }
        });

        btnDeleteItem.setText("Delete Item");
        btnDeleteItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteItemActionPerformed(evt);
            }
        });

        btnDecrement.setText("Decrement");
        btnDecrement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecrementActionPerformed(evt);
            }
        });

        jLabel7.setText("Deletes item selected from list ");

        jLabel8.setText("Decrements inventory count of item selected from the list");

        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        rdbtnTrees.setText("Trees");
        rdbtnTrees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnTreesActionPerformed(evt);
            }
        });

        rdbtnSeeds.setText("Seeds");
        rdbtnSeeds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnSeedsActionPerformed(evt);
            }
        });

        rdbtnShrubs.setText("Shrubs");
        rdbtnShrubs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnShrubsActionPerformed(evt);
            }
        });

        rdbtnCultureBoxes.setText("Culture Boxes");
        rdbtnCultureBoxes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnCultureBoxesActionPerformed(evt);
            }
        });

        rdbtnGenomics.setText("Genomics");
        rdbtnGenomics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnGenomicsActionPerformed(evt);
            }
        });

        rdbtnProcessing.setText("Processing");
        rdbtnProcessing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnProcessingActionPerformed(evt);
            }
        });

        rdbtnRefMaterials.setText("Reference Materials");
        rdbtnRefMaterials.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnRefMaterialsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(324, 324, 324)
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 281, Short.MAX_VALUE)
                            .addComponent(btnLogOut)
                            .addGap(27, 27, 27))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4))
                                    .addGap(5, 5, 5))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtProdDescription)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtDBIP, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnProdQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(rdbtnShrubs)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(rdbtnProcessing))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(236, 236, 236)
                                            .addComponent(rdbtnRefMaterials)))
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtProdPrice)
                                        .addComponent(txtProdID, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(rdbtnSeeds)
                                            .addGap(17, 17, 17)
                                            .addComponent(rdbtnGenomics))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(rdbtnTrees)
                                            .addGap(18, 18, 18)
                                            .addComponent(rdbtnCultureBoxes)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnAddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(btnDeleteItem, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel7))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnListInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(btnDecrement, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1152, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(btnLogOut))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtDBIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtProdDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtProdID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(rdbtnTrees)
                            .addComponent(rdbtnCultureBoxes))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtProdPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(rdbtnSeeds)
                            .addComponent(rdbtnGenomics)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(btnDeleteItem, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(btnDecrement)
                            .addComponent(btnListInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(btnProdQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdbtnShrubs)
                    .addComponent(rdbtnProcessing))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbtnRefMaterials)
                .addGap(15, 15, 15)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Added by Robin
    private int getProductSelection() {
        int curSel = InventoryView.PROD_CATEGORY_NO_SEL;
        
        if (rdbtnTrees.isSelected()) {
            curSel = InventoryView.PROD_CATEGORY_TREES;
        } else if (rdbtnSeeds.isSelected()) {
            curSel = InventoryView.PROD_CATEGORY_SEEDS;
        } else if (rdbtnShrubs.isSelected()) {
            curSel = InventoryView.PROD_CATEGORY_SHRUBS;
        } else if (rdbtnCultureBoxes.isSelected()) {
            curSel = InventoryView.PROD_CATEGORY_CULTURE_BOXES;
        } else if (rdbtnGenomics.isSelected()) {
            curSel = InventoryView.PROD_CATEGORY_GENOMICS;
        } else if (rdbtnProcessing.isSelected()) {
            curSel = InventoryView.PROD_CATEGORY_PROCESSING;
        } else if (rdbtnRefMaterials.isSelected()) {
            curSel = InventoryView.PROD_CATEGORY_REFERENCE_MATERIALS;
        } else {
            // Empty
        }
        
        return curSel;
    }
    
    private void btnAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddItemActionPerformed

        // Adds inventory to database

        Boolean connectError = false;   // Error flag
        Connection DBConn = null;       // MySQL connection handle
        String description;             // Tree, seed, or shrub description
        Boolean executeError = false;   // Error flag
        String errString = null;        // String for displaying errors
        int executeUpdateVal;           // Return value from execute indicating effected rows
        Boolean fieldError = false;     // Error flag
        String msgString = null;        // String for displaying non-error messages
        ResultSet res = null;           // SQL query result set pointer
        String tableSelected = null;    // String used to determine which data table to use
        Integer quantity;               // Quantity of trees, seeds, or shrubs
        Float perUnitCost;              // Cost per tree, seed, or shrub unit
        String productID = null;        // Product id of tree, seed, or shrub
        java.sql.Statement s = null;    // SQL statement pointer
        String SQLstatement = null;     // String for building SQL queries
        
        // Check to make sure a radio button is selected
       
        txtMessageArea.setText("");
        
        int currProdSel = getProductSelection();
        
        if (currProdSel == InventoryView.PROD_CATEGORY_NO_SEL)
        {
            fieldError = true;
            txtMessageArea.append("\n" + ERR_MSG_INVALID_PROD_SELECTION);
        } else {
       
            //Make sure there is a product description
            if ( txtProdDescription.getText().length() == 0 )
            {
                fieldError = true;
                txtMessageArea.append("\nMust enter a product description.");
                
            } else {
     
                //Make sure there is a product ID
                if ( txtProdID.getText().length() == 0 )
                {
                    fieldError = true;
                    txtMessageArea.append("\nMust enter a product ID.");
                } else {
            
                    //Make sure there is a price
                    if ( txtProdPrice.getText().length() == 0 )
                    {
                        fieldError = true;
                        txtMessageArea.append("\nMust enter a product price.");
                    } else {
                    
                        //Make sure quantity is specified
                        if ( btnProdQuantity.getText().length() == 0 )
                        {
                            fieldError = true;
                            txtMessageArea.append("\nMust enter a product quantity.");
                        } // quantity
                    } // price
                } // product ID
            } //product description
        } //category selected

        //Now, if there was no error in the data fields, we try to
        //connect to the database.
        
        if ( !fieldError )
        {
            try
            {
                msgString = ">> Establishing Driver...";
                txtMessageArea.setText("\n"+msgString);

                //load JDBC driver class for MySQL
                Class.forName( "com.mysql.jdbc.Driver" );

                msgString = ">> Setting up URL...";
                txtMessageArea.append("\n"+msgString);

                //define the data source
                String SQLServerIP = txtDBIP.getText();
                String sourceURL = "jdbc:mysql://" + SQLServerIP + ":3306/" + 
                        this.getInventoryDatabaseName(currProdSel);

                msgString = ">> Establishing connection with: " + sourceURL + "...";
                txtMessageArea.append("\n"+msgString);

                //create a connection to the db
                DBConn = DriverManager.getConnection(sourceURL,"remote","remote_pass");

            } catch (Exception e) {

                errString =  "\nProblem connecting to database:: " + e;
                txtMessageArea.append(errString);
                connectError = true;

            } // end try-catch
        } // fieldError check

        //If there is not connection error, then we form the SQL statement
        //and then execute it.

        if (!connectError && !fieldError )
        {
            try
            {
                // get the data from the text fields
                description = txtProdDescription.getText();
                productID = txtProdID.getText();
                quantity = Integer.parseInt(btnProdQuantity.getText());
                perUnitCost = Float.parseFloat(txtProdPrice.getText());

                // create an SQL statement variable and create the INSERT
                // query to insert the new inventory into the database

                s = DBConn.createStatement();

                // if trees are selected then insert inventory into trees
                // table
                if (currProdSel == InventoryView.PROD_CATEGORY_TREES)
                {
                    SQLstatement = ( "INSERT INTO trees (product_code, " +
                            "description, quantity, price) VALUES ( '" +
                            productID + "', " + "'" + description + "', " +
                            quantity + ", " + perUnitCost + ");");
                    
                    tableSelected = "TREES";

                }

                // if shrubs are selected then insert inventory into strubs
                // table
                if (currProdSel == InventoryView.PROD_CATEGORY_SHRUBS)
                {
                    SQLstatement = ( "INSERT INTO shrubs (product_code, " +
                            "description, quantity, price) VALUES ( '" +
                            productID + "', " + "'" + description + "', " +
                            quantity + ", " + perUnitCost + ");");
                    
                    tableSelected = "SHRUBS";
                }

                // if seeds are selected then insert inventory into seeds
                // table
                if (currProdSel == InventoryView.PROD_CATEGORY_SEEDS)
                {
                    SQLstatement = ( "INSERT INTO seeds (product_code, " +
                            "description, quantity, price) VALUES ( '" +
                            productID + "', " + "'" + description + "', " +
                            quantity + ", " + perUnitCost + ");");
                    
                    tableSelected = "SEEDS";
                }

                // if culture boxes are selected then insert inventory into cultureboxes 
                // table

                if (currProdSel == InventoryView.PROD_CATEGORY_CULTURE_BOXES)
                {
                    SQLstatement = ( "INSERT INTO cultureboxes (productid, " +
                            "productdescription, productquantity, productprice) VALUES ( '" +
                            productID + "', " + "'" + description + "', " +
                            quantity + ", " + perUnitCost + ");");
        
                    tableSelected = "CULTURE BOXES";
                }

                // if processing equipment is selected then insert inventory into strubs
                // table

                if (currProdSel == InventoryView.PROD_CATEGORY_PROCESSING)
                {
                    SQLstatement = ( "INSERT INTO processing (productid, " +
                            "productdescription, productquantity, productprice) VALUES ( '" +
                            productID + "', " + "'" + description + "', " +
                            quantity + ", " + perUnitCost + ");");
                    
                    tableSelected = "PROCESSING";
                }

                // if genomics are selected then insert inventory into the genomics
                // table

                if (currProdSel == InventoryView.PROD_CATEGORY_GENOMICS)
                {
                    SQLstatement = ( "INSERT INTO genomics (productid, " +
                            "productdescription, productquantity, productprice) VALUES ( '" +
                            productID + "', " + "'" + description + "', " +
                            quantity + ", " + perUnitCost + ");");
                
                    tableSelected = "GENOMICS";
                }

                // if reference materials are selected then insert inventory into referencematerials
                // table

                if (currProdSel == InventoryView.PROD_CATEGORY_REFERENCE_MATERIALS)
                {
                    SQLstatement = ( "INSERT INTO referencematerials (productid, " +
                            "productdescription, productquantity, productprice) VALUES ( '" +
                            productID + "', " + "'" + description + "', " +
                            quantity + ", " + perUnitCost + ");");
                    
                    tableSelected = "REFERENCE MATERIALS";
                }
                
                // execute the update
                executeUpdateVal = s.executeUpdate(SQLstatement);

                // let the user know all went well

                txtMessageArea.append("\nINVENTORY UPDATED... The following was added to the " + tableSelected + " inventory...\n");
                txtMessageArea.append("\nProduct Code:: " + productID);
                txtMessageArea.append("\nDescription::  " + description);
                txtMessageArea.append("\nQuantity::     " + quantity);
                txtMessageArea.append("\nUnit Cost::    " + perUnitCost);

            } catch (Exception e) {

                errString =  "\nProblem adding inventory:: " + e;
                txtMessageArea.append(errString);
                executeError = true;

            } // try

        } //execute SQL check

    }//GEN-LAST:event_btnAddItemActionPerformed
    
    private static final int PROD_CATEGORY_NO_SEL = -1; // No selection at all.
//    private static final int PROD_CATEGORY_BLANK = 0;   // Blank string
    private static final int PROD_CATEGORY_TREES = 1;
    private static final int PROD_CATEGORY_SEEDS = 2;
    private static final int PROD_CATEGORY_SHRUBS = 3;
    private static final int PROD_CATEGORY_CULTURE_BOXES = 4;
    private static final int PROD_CATEGORY_GENOMICS = 5;
    private static final int PROD_CATEGORY_PROCESSING = 6;
    private static final int PROD_CATEGORY_REFERENCE_MATERIALS = 7;
    
    private String getInventoryDatabaseName(int prodCategorySel)
    {
        String dbName;
        
        switch(prodCategorySel)
        {
            case InventoryView.PROD_CATEGORY_TREES:
                // Fall through
            case InventoryView.PROD_CATEGORY_SEEDS:
                // Fall through
            case InventoryView.PROD_CATEGORY_SHRUBS:
                dbName = "inventory";
                break;
            case InventoryView.PROD_CATEGORY_CULTURE_BOXES:
                // Fall through
            case InventoryView.PROD_CATEGORY_GENOMICS:
                // Fall through
            case InventoryView.PROD_CATEGORY_PROCESSING:
                // Fall through
            case InventoryView.PROD_CATEGORY_REFERENCE_MATERIALS:
                dbName = "leaftech";
                break;
            default:
                dbName = "";
        }
        
        return dbName;
    }
    
    private void btnListInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListInventoryActionPerformed
        // This button will list the inventory for the product selected by the
        // radio button

        Boolean connectError = false;   // Error flag
        Connection DBConn = null;       // MySQL connection handle
        Boolean executeError = false;   // Error flag
        String errString = null;        // String for displaying errors
        Boolean fieldError = true;      // Error flag
        String msgString = null;        // String for displaying non-error messages
        ResultSet res = null;           // SQL query result set pointer
        String tableSelected = null;    // String used to determine which data table to use
        java.sql.Statement s = null;    // SQL statement pointer

        // Check to make sure a radio button is selected
//        if (jRadioButton1.isSelected() || jRadioButton2.isSelected() || jRadioButton3.isSelected())
//        {
//            fieldError = false;
//
//        } else {
//
//            msgString = "Must select Tree, Seeds, or Shrubs radio button.";
//            txtMessageArea.setText("\n"+msgString);
//        }
        
        int currProdSel;
        currProdSel = getProductSelection();
        if (currProdSel != InventoryView.PROD_CATEGORY_NO_SEL)
        {
            fieldError = false;
        } else {
            msgString = ERR_MSG_INVALID_PROD_SELECTION;
            txtMessageArea.setText("\n"+msgString);
        }

        //Now, we try to connect to the inventory database.
        if (!fieldError)
        {
            //Clear the fields - they are not needed and may cause confusion
            txtProdID.setText("");
            txtProdPrice.setText("");
            btnProdQuantity.setText("");
            txtProdDescription.setText("");
            txtMessageArea.setText("");
            
            try
            {
                msgString = ">> Establishing Driver...";
                txtMessageArea.setText("\n"+msgString);

                //load JDBC driver class for MySQL
                Class.forName( "com.mysql.jdbc.Driver" );

                msgString = ">> Setting up URL...";
                txtMessageArea.append("\n"+msgString);

                //define the data source
                String SQLServerIP = txtDBIP.getText();
                String sourceURL = "jdbc:mysql://" + SQLServerIP + ":3306/" + getInventoryDatabaseName(currProdSel);

                msgString = ">> Establishing connection with: " + sourceURL + "...";
                txtMessageArea.append("\n"+msgString);

                //create a connection to the db
                DBConn = DriverManager.getConnection(sourceURL,"remote","remote_pass");

            } catch (Exception e) {

                errString =  "\nProblem connecting to database:: " + e;
                txtMessageArea.append(errString);
                connectError = true;

            } // end try-catch

        } // fielderror check - make sure a product is selected
    
        //If there is not connection error, then we form the SQL statement
        //and then execute it.

        if (!connectError && !fieldError)
        {
            try
            {
                // create an SQL statement variable and create the INSERT
                // query to insert the new inventory into the database

                s = DBConn.createStatement();

                // now we build a query to list the inventory table contents
                // for the user
                // ... here is the SQL for trees
                if (currProdSel == InventoryView.PROD_CATEGORY_TREES)
                {
                    res = s.executeQuery( "Select * from trees" );
                    tableSelected = "TREE";
                }
                // ... here is the SQL for shrubs
                if (currProdSel == InventoryView.PROD_CATEGORY_SHRUBS)
                {
                    res = s.executeQuery( "Select * from shrubs" );
                    tableSelected = "SHRUB";
                }
                // ... here is the SQL for seeds
                if (currProdSel == InventoryView.PROD_CATEGORY_SEEDS)
                {
                    res = s.executeQuery( "Select * from seeds" );
                    tableSelected = "SEED";
                }
                // ... here is the SQL for Culture Boxes
                if (currProdSel == InventoryView.PROD_CATEGORY_CULTURE_BOXES)
                {
                    res = s.executeQuery( "Select * from cultureboxes" );
                    tableSelected = "CULTURE BOXES";
                }
                // ... here is the SQL for Genomics
                if (currProdSel == InventoryView.PROD_CATEGORY_GENOMICS)
                {
                    res = s.executeQuery( "Select * from genomics" );
                    tableSelected = "GENOMICS";
                }
                // ... here is the SQL for Processing
                if (currProdSel == InventoryView.PROD_CATEGORY_PROCESSING)
                {
                    res = s.executeQuery( "Select * from processing" );
                    tableSelected = "PROCESSING";
                }
                // ... here is the SQL for Reference Materials
                if (currProdSel == InventoryView.PROD_CATEGORY_REFERENCE_MATERIALS)
                {
                    res = s.executeQuery( "Select * from referencematerials" );
                    tableSelected = "REFERENCE MATERIALS";
                }

                // Now we list the inventory for the selected table
                txtMessageArea.setText("");
                while (res.next())
                {
                    msgString = tableSelected+">>" + res.getString(1) + "::" + res.getString(2) +
                            " :: "+ res.getString(3) + "::" + res.getString(4);
                    txtMessageArea.append("\n"+msgString);

                } // while

            } catch(Exception e) {

                errString =  "\nProblem with " + tableSelected +" query:: " + e;
                txtMessageArea.append(errString);
                executeError = true;

            } // try
        }
    }//GEN-LAST:event_btnListInventoryActionPerformed
    private static final String ERR_MSG_INVALID_PROD_SELECTION = "Must select Tree, Seeds, Shrubs, Culture Boxes, Genomics, Processing, Reference Materials.";

    private void btnDeleteItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteItemActionPerformed
        // Deletes an item from the database
        
        int beginIndex;                     // Parsing index
        int endIndex;                       // Parsing index
        String productID = null;            // Product ID pnemonic
        Boolean IndexNotFound;              // Flag indicating a string index was not found.
        Boolean connectError = false;       // Error flag
        Connection DBConn = null;           // MySQL connection handle
        String errString = null;            // String for displaying errors
        int executeUpdateVal;               // Return value from execute indicating effected rows
        String msgString = null;            // String for displaying non-error messages
        String tableSelected = null;        // String used to determine which data table to use
        java.sql.Statement s = null;        // SQL statement pointer
        String SQLstatement = null;         // String for building SQL queries
        String inventorySelection = null;   // Inventory text string selected by user
        IndexNotFound = false;              // Flag indicating that a string index was not found
        
        // If we can arrive here, that means a product category had
        // been selected.
        int currProdSel = this.getProductSelection();
        if (currProdSel == InventoryView.PROD_CATEGORY_NO_SEL)
        {
            msgString = ERR_MSG_INVALID_PROD_SELECTION;
            txtMessageArea.setText("\n"+msgString);
            return;
        }
        
        // this is the selected line of text
        inventorySelection =  txtMessageArea.getSelectedText();

        // make sure the selection is not blank
        if ( inventorySelection != null )
        {
            // get the product ID - here we get the leading index
            beginIndex = 0;
            endIndex = inventorySelection.indexOf(">>",beginIndex);

            if (endIndex < 0 ) {
                IndexNotFound = true;
            } else {
                beginIndex = endIndex+2; //skip past ">>"                                
            }
            
            if ( !IndexNotFound )
            {
                // Here we get the trailing index and parse out the productID
                endIndex = inventorySelection.indexOf(":",beginIndex);

                if (endIndex < 0 ) {
                    IndexNotFound = true;
                } else {
                    productID = inventorySelection.substring(beginIndex,endIndex);
                }              
            }
           
            // Now we delete the inventory item indicated by the productID we
            // parsed out above from the indicated table.
            
            if ( !IndexNotFound )
            {   
                txtMessageArea.setText("");
                txtMessageArea.append( "Deleting ProductID: " + productID );

                // set up a connection to the LeafTech database
                try
                {                
                    //load JDBC driver class for MySQL
                    Class.forName( "com.mysql.jdbc.Driver" );

                    //define the data source
                    String SQLServerIP = txtDBIP.getText();
                    String sourceURL = "jdbc:mysql://" + SQLServerIP + ":3306/" +
                            this.getInventoryDatabaseName(currProdSel);

                    //create a connection to the db
                    DBConn = DriverManager.getConnection(sourceURL,"remote","remote_pass");

                } catch (Exception e) {

                    errString =  "\nProblem connecting to database:: " + e;
                    txtMessageArea.append(errString);
                    connectError = true;

                } // end try-catch
                
                //If there is no connection error, then we form the SQL statement
                //to delete the inventory item and then execute it.

                if (!connectError )
                {
                    try
                    {
                        s = DBConn.createStatement();

                        // if trees inventory selected
                        if (currProdSel == InventoryView.PROD_CATEGORY_TREES)
                        {
                            SQLstatement = ( "DELETE FROM trees WHERE product_code = '" + productID + "';");
                        }

                        // if shrubs inventory selected
                        if (currProdSel == InventoryView.PROD_CATEGORY_SHRUBS)
                        {
                            SQLstatement = ( "DELETE FROM shrubs WHERE product_code = '" + productID + "';");
                        }

                        // if seeds inventory selected
                        if (currProdSel == InventoryView.PROD_CATEGORY_SEEDS)
                        {
                            SQLstatement = ( "DELETE FROM seeds WHERE product_code = '" + productID + "';");
                        }
                        
                        // if culture boxes inventory selected
                        if (currProdSel == InventoryView.PROD_CATEGORY_CULTURE_BOXES)
                        {
                            SQLstatement = ( "DELETE FROM cultureboxes WHERE productid = '" + productID + "';");
                        }

                        // if processing equipment inventory selected
                        if (currProdSel == InventoryView.PROD_CATEGORY_PROCESSING)
                        {
                            SQLstatement = ( "DELETE FROM processing WHERE productid = '" + productID + "';");
                        }

                        // if genomics inventory selected
                        if (currProdSel == InventoryView.PROD_CATEGORY_GENOMICS)
                        {
                            SQLstatement = ( "DELETE FROM genomics WHERE productid = '" + productID + "';");
                        }

                        // if reference materials  inventory selected
                        if (currProdSel == InventoryView.PROD_CATEGORY_REFERENCE_MATERIALS)
                        {
                            SQLstatement = ( "DELETE FROM referencematerials WHERE productid = '" + productID + "';");
                        }
   
                        // execute the delete query
                        
                        executeUpdateVal = s.executeUpdate(SQLstatement);

                        // let the user know all went well
                        
                        txtMessageArea.append("\n\n" + productID + " deleted...");
                        txtMessageArea.append("\n Number of items deleted: " + executeUpdateVal );


                    } catch (Exception e) {

                        errString =  "\nProblem with delete:: " + e;
                        txtMessageArea.append(errString);

                    } // try
               
                } // connection check    
                                       
            } else {

                txtMessageArea.setText("");
                txtMessageArea.append("\nNo items selected...\nSELECT ENTIRE INVENTORY LINE TO ADD ITEM TO ORDER\n(TRIPLE CLICK ITEM LINE)");      

            }
        } else {

            txtMessageArea.setText("");
            txtMessageArea.append("\nNo items selected...\nSELECT ENTIRE INVENTORY LINE TO ADD ITEM TO ORDER\n(TRIPLE CLICK ITEM LINE)"); 

        } // Blank string check        
        
    }//GEN-LAST:event_btnDeleteItemActionPerformed

    private void btnDecrementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecrementActionPerformed
        // Decrements the inventory count for a selected item
        int beginIndex;                     // Parsing index
        int endIndex;                       // Parsing index
        String productID = null;            // Product ID pnemonic
        Boolean IndexNotFound;              // Flag indicating a string index was not found.
        Boolean connectError = false;       // Error flag
        Connection DBConn = null;           // MySQL connection handle
        String errString = null;            // String for displaying errors
        int executeUpdateVal;               // Return value from execute indicating effected rows
        String msgString = null;            // String for displaying non-error messages
        ResultSet res = null;               // SQL query result set pointer
        String tableSelected = null;        // String used to determine which data table to use
        java.sql.Statement s = null;        // SQL statement pointer
        String SQLstatement1 = null;        // String for building SQL queries
        String SQLstatement2 = null;        // String for building SQL queries
        String inventorySelection = null;   // Inventory text string selected by user
        IndexNotFound = false;              // Flag indicating that a string index was not found
        
        // If we can arrive here, that means a product category had
        // been selected.
        int currProdSel = this.getProductSelection();
        if (currProdSel == InventoryView.PROD_CATEGORY_NO_SEL)
        {
            msgString = ERR_MSG_INVALID_PROD_SELECTION;
            txtMessageArea.setText("\n"+msgString);
            return;
        }
        
        // this is the selected line of text
        inventorySelection =  txtMessageArea.getSelectedText();

        // make sure the selection is not blank
        if ( inventorySelection != null )
        {
            // get the product ID - here we get the leading index
            beginIndex = 0;
            endIndex = inventorySelection.indexOf(">>",beginIndex);

            if (endIndex < 0 ) {
                IndexNotFound = true;
            } else {
                beginIndex = endIndex+2; //skip past ">>"                                
            }
            
            if ( !IndexNotFound )
            {
                // Here we get the trailing index and parse out the productID
                endIndex = inventorySelection.indexOf(":",beginIndex);

                if (endIndex < 0 ) {
                    IndexNotFound = true;
                } else {
                    productID = inventorySelection.substring(beginIndex,endIndex);
                }              
            }
           
            // Now we decrement the inventory count of the item indicated by the productID we
            // parsed out above from the indicated table.
            
            if ( !IndexNotFound )
            {
                txtMessageArea.setText("");
                txtMessageArea.append( "Deleting ProductID: " + productID );

                // set up a connection to the LeafTech database
                try
                {                
                    //load JDBC driver class for MySQL
                    Class.forName( "com.mysql.jdbc.Driver" );

                    //define the data source
                    String SQLServerIP = txtDBIP.getText();
                    String sourceURL = "jdbc:mysql://" + SQLServerIP + ":3306/" + 
                            this.getInventoryDatabaseName(currProdSel);

                    //create a connection to the db
                    DBConn = DriverManager.getConnection(sourceURL,"remote","remote_pass");

                } catch (Exception e) {

                    errString =  "\nProblem connecting to database:: " + e;
                    txtMessageArea.append(errString);
                    connectError = true;

                } // end try-catch
                
                //If there is no connection error, then we form the SQL statement
                //to decrement the inventory item count and then execute it.

                if (!connectError )
                {
                    try
                    {
                        s = DBConn.createStatement();

                        // if trees inventory selected
                        if (currProdSel == InventoryView.PROD_CATEGORY_TREES)
                        {
                            SQLstatement1 = ("UPDATE trees set quantity=(quantity-1) where product_code = '" + productID + "';");
                            SQLstatement2 = ("SELECT * from trees where product_code = '" + productID + "';");
                            tableSelected = "TREES";
                        }

                        // if strubs inventory selected
                        if (currProdSel == InventoryView.PROD_CATEGORY_SHRUBS)
                        {
                            SQLstatement1 = ("UPDATE shrubs set quantity=(quantity-1) where product_code = '" + productID + "';");
                            SQLstatement2 = ("SELECT * from shrubs where product_code = '" + productID + "';");
                            tableSelected = "SHRUBS";
                        }

                        // if seeds inventory selected
                        if (currProdSel == InventoryView.PROD_CATEGORY_SEEDS)
                        {
                            SQLstatement1 = ("UPDATE seeds set quantity=(quantity-1) where product_code = '" + productID + "';");
                            SQLstatement2 = ("SELECT * from seeds where product_code = '" + productID + "';");
                            tableSelected = "SEEDS";
                        }
                        
                        // if culture boxes inventory selected
                        if (currProdSel == InventoryView.PROD_CATEGORY_CULTURE_BOXES)
                        {
                            SQLstatement1 = ("UPDATE cultureboxes set productquantity=(productquantity-1) where productid = '" + productID + "';");
                            SQLstatement2 = ("SELECT * from cultureboxes where productid = '" + productID + "';");
                            tableSelected = "CULTURE BOXES";
                        }

                        // if processing equipment inventory selected
                        if (currProdSel == InventoryView.PROD_CATEGORY_PROCESSING)
                        {
                            SQLstatement1 = ("UPDATE processing set productquantity=(productquantity-1) where productid = '" + productID + "';");
                            SQLstatement2 = ("SELECT * from processing where productid = '" + productID + "';");
                            tableSelected = "PROCESSING";
                        }

                        // if genomics inventory selected
                        if (currProdSel == InventoryView.PROD_CATEGORY_GENOMICS)
                        {
                            SQLstatement1 = ("UPDATE genomics set productquantity=(productquantity-1) where productid = '" + productID + "';");
                            SQLstatement2 = ("SELECT * from genomics where productid = '" + productID + "';");
                            tableSelected = "GENOMICS";
                        }

                        // if reference materials  inventory selected
                        if (currProdSel == InventoryView.PROD_CATEGORY_REFERENCE_MATERIALS)
                        {
                            SQLstatement1 = ("UPDATE referencematerials set productquantity=(productquantity-1) where productid = '" + productID + "';");
                            SQLstatement2 = ("SELECT * from referencematerials where productid = '" + productID + "';");
                            tableSelected = "REFERENCE MATERIALS";
                        }

                        // execute the update, then query the BD for the table entry for the item just changed
                        // and display it for the user
                        
                        executeUpdateVal = s.executeUpdate(SQLstatement1);
                        res = s.executeQuery(SQLstatement2);
                       
                        
                        txtMessageArea.append("\n\n" + productID + " inventory decremented...");
                        
                        while (res.next())
                        {
                            msgString = tableSelected + ">> " + res.getString(1) + " :: " + res.getString(2) +
                            " :: "+ res.getString(3) + " :: " + res.getString(4);
                            txtMessageArea.append("\n"+msgString);

                        } // while
                        
                        txtMessageArea.append("\n\n Number of items updated: " + executeUpdateVal );

                    } catch (Exception e) {

                        errString =  "\nProblem with delete:: " + e;
                        txtMessageArea.append(errString);

                    } // try
               
                } // connection check    
                                       
            } else {

                txtMessageArea.setText("");
                txtMessageArea.append("\nNo items selected...\nSELECT ENTIRE INVENTORY LINE TO ADD ITEM TO ORDER\n(TRIPLE CLICK ITEM LINE)");      

            }
        } else {

            txtMessageArea.setText("");
            txtMessageArea.append("\nNo items selected...\nSELECT ENTIRE INVENTORY LINE TO ADD ITEM TO ORDER\n(TRIPLE CLICK ITEM LINE)"); 

        } // Blank string check
    }//GEN-LAST:event_btnDecrementActionPerformed

    private void txtProdDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProdDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProdDescriptionActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        controller.logOut();
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        controller.logOut();
    }//GEN-LAST:event_formWindowClosing

    private void rdbtnTreesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnTreesActionPerformed
        rdbtnCultureBoxes.setSelected(false);
        rdbtnGenomics.setSelected(false);
        rdbtnProcessing.setSelected(false);
        rdbtnRefMaterials.setSelected(false);
        rdbtnSeeds.setSelected(false);
        rdbtnShrubs.setSelected(false);
        rdbtnTrees.setSelected(true);
    }//GEN-LAST:event_rdbtnTreesActionPerformed

    private void rdbtnSeedsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnSeedsActionPerformed
        rdbtnCultureBoxes.setSelected(false);
        rdbtnGenomics.setSelected(false);
        rdbtnProcessing.setSelected(false);
        rdbtnRefMaterials.setSelected(false);
        rdbtnSeeds.setSelected(true);
        rdbtnShrubs.setSelected(false);
        rdbtnTrees.setSelected(false);
    }//GEN-LAST:event_rdbtnSeedsActionPerformed

    private void rdbtnShrubsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnShrubsActionPerformed
        rdbtnCultureBoxes.setSelected(false);
        rdbtnGenomics.setSelected(false);
        rdbtnProcessing.setSelected(false);
        rdbtnRefMaterials.setSelected(false);
        rdbtnSeeds.setSelected(false);
        rdbtnShrubs.setSelected(true);
        rdbtnTrees.setSelected(false);
    }//GEN-LAST:event_rdbtnShrubsActionPerformed

    private void rdbtnCultureBoxesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnCultureBoxesActionPerformed
        rdbtnCultureBoxes.setSelected(true);
        rdbtnGenomics.setSelected(false);
        rdbtnProcessing.setSelected(false);
        rdbtnRefMaterials.setSelected(false);
        rdbtnSeeds.setSelected(false);
        rdbtnShrubs.setSelected(false);
        rdbtnTrees.setSelected(false);
    }//GEN-LAST:event_rdbtnCultureBoxesActionPerformed

    private void rdbtnGenomicsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnGenomicsActionPerformed
        rdbtnCultureBoxes.setSelected(false);
        rdbtnGenomics.setSelected(true);
        rdbtnProcessing.setSelected(false);
        rdbtnRefMaterials.setSelected(false);
        rdbtnSeeds.setSelected(false);
        rdbtnShrubs.setSelected(false);
        rdbtnTrees.setSelected(false);
    }//GEN-LAST:event_rdbtnGenomicsActionPerformed

    private void rdbtnProcessingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnProcessingActionPerformed
        rdbtnCultureBoxes.setSelected(false);
        rdbtnGenomics.setSelected(false);
        rdbtnProcessing.setSelected(true);
        rdbtnRefMaterials.setSelected(false);
        rdbtnSeeds.setSelected(false);
        rdbtnShrubs.setSelected(false);
        rdbtnTrees.setSelected(false);
    }//GEN-LAST:event_rdbtnProcessingActionPerformed

    private void rdbtnRefMaterialsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnRefMaterialsActionPerformed
        rdbtnCultureBoxes.setSelected(false);
        rdbtnGenomics.setSelected(false);
        rdbtnProcessing.setSelected(false);
        rdbtnRefMaterials.setSelected(true);
        rdbtnSeeds.setSelected(false);
        rdbtnShrubs.setSelected(false);
        rdbtnTrees.setSelected(false);
    }//GEN-LAST:event_rdbtnRefMaterialsActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddItem;
    private javax.swing.JButton btnDecrement;
    private javax.swing.JButton btnDeleteItem;
    private javax.swing.JButton btnListInventory;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JTextField btnProdQuantity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton rdbtnCultureBoxes;
    private javax.swing.JRadioButton rdbtnGenomics;
    private javax.swing.JRadioButton rdbtnProcessing;
    private javax.swing.JRadioButton rdbtnRefMaterials;
    private javax.swing.JRadioButton rdbtnSeeds;
    private javax.swing.JRadioButton rdbtnShrubs;
    private javax.swing.JRadioButton rdbtnTrees;
    private javax.swing.JTextField txtDBIP;
    private javax.swing.JTextArea txtMessageArea;
    private javax.swing.JTextField txtProdDescription;
    private javax.swing.JTextField txtProdID;
    private javax.swing.JTextField txtProdPrice;
    // End of variables declaration//GEN-END:variables

}
